# -*- coding: utf-8 -*-

from typing import Union

from sqlglot import exp, parse_one

from veloxdf.ast import Alias, BinaryOp, Column, Expression, FunctionCall, Literal


def _parse_literal_value(value_str: str, is_string_literal: bool):
    """
    Parses a string value from sqlglot into a Python native type.
    Tries to convert to int, then float, otherwise keeps it as a string.
    """
    if is_string_literal:
        return value_str

    try:
        return int(value_str)
    except ValueError:
        try:
            return float(value_str)
        except ValueError:
            return value_str


class ExpressionParser:
    """
    Parses SQL expression strings into this project's custom Expression AST
    by transforming the AST generated by the sqlglot library.
    """

    def parse(self, sql_string: str) -> Expression:
        """
        Parses a single SQL expression string.

        Args:
            sql_string: The SQL expression to parse (e.g., "c0 > 10", "c1 + 1 as c2").

        Returns:
            An Expression node from our custom AST.
        """
        sqlglot_ast = parse_one(sql_string, read="presto")
        return self._transform(sqlglot_ast)

    def _transform(self, node: Union[exp.Expression, str]) -> Expression:
        """
        Recursively transforms a sqlglot AST node into our custom Expression AST node.
        """
        if isinstance(node, (exp.Column, exp.Identifier, exp.Dot)):
            return Column(name=node.sql())

        if isinstance(node, exp.Literal):
            value = _parse_literal_value(node.this, node.is_string)
            return Literal(value=value)

        if isinstance(node, str):
            return Literal(value=node)

        if isinstance(node, exp.Binary):
            op_map = {
                exp.GT: ">",
                exp.GTE: ">=",
                exp.LT: "<",
                exp.LTE: "<=",
                exp.EQ: "==",
                exp.NEQ: "!=",
                exp.And: "and",
                exp.Or: "or",
                exp.Add: "+",
                exp.Sub: "-",
                exp.Mul: "*",
                exp.Div: "/",
            }
            op_symbol = op_map.get(type(node))
            if not op_symbol:
                raise NotImplementedError(f"Unsupported binary operator: {type(node)}")

            return BinaryOp(
                left=self._transform(node.left),
                op=op_symbol,
                right=self._transform(node.right),
            )

        if isinstance(node, exp.StartsWith):
            return FunctionCall(
                name="STARTS_WITH",
                args=[self._transform(node.this), self._transform(node.expression)],
            )

        if isinstance(node, exp.Func):
            # Special case: ArraySize (maps to cardinality) has its argument in .this
            if isinstance(node, exp.ArraySize):
                return FunctionCall(name="CARDINALITY", args=[self._transform(node.this)])

            func_name = node.this.name.upper()
            return FunctionCall(name=func_name, args=[self._transform(arg) for arg in node.args])

        # Handle aliases (e.g., "col as new_col")
        if isinstance(node, exp.Alias):
            return Alias(child=self._transform(node.this), alias=node.alias)

        raise TypeError(f"Cannot parse sqlglot node type: {type(node)}")
